### ISSUE TITLE
Unexpected rapid fire behaviour with any right-click interaction.

### ISSUE THREAD

**Issue by SodiumShine** [Fuzss/proplacer#1]
Anything that uses right clicking can be triggered _extremely_ fast, not just block placement. All the following normally includes a delay even if you're holding down the right mouse button. 
- Certain projectiles like eggs, snowballs and potions go off like a gatling gun. It also happens with mod items like the throwable brick from Supplementaries, or AE2's matter cannon.
- Blocks that can be interacted with, like doors, bells, levers etc can be triggered at the same speed.
- It also happens with magic spells from mods like Ars Nouveau

This is probably fine for vanilla but it makes mod interaction risky depending on what items a mod adds. 

If possible some configuration options would be good, but I understand if that's outside the scope of the mod.

**Comment by Fuzss** [comment]
Mod is discontinued now.

**Comment by Fuzss** [comment]
Fixed for the 1.20+ version, thanks!
