### ISSUE TITLE
[Suggestion] Just bring it back to life

### ISSUE THREAD

**Issue by DanteTooMayCry** [Fuzss/proplacer#2]
It's sad that the mod hasn't been updated for so long. It was the best mod of this type.

**Comment by Fuzss** [comment]
The mod has been rewritten for 1.20.1 now and is available for Forge & Fabric. You can find downloads for a preview on our Discord: https://lunapixel.studio/discord

Also pinging @mynameisjeoff23.

I want to try and add a couple new features before a public release.

**Comment by Fuzss** [comment]
Full version has been uploaded to CurseForge (Modrinth not yet approved) with fast block breaking for creative mode and reach-around block placement for easy bridging just like Bedrock Edition.
