### ISSUE TITLE
[Bug]: cant shoot bow if i look down, and i think this bug would also affact other items that are used with right click such as ender pearls.

### ISSUE THREAD

**Issue by lalelilolu2** [Fuzss/proplacer#3]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

8.0.1

### Minimal Setup (Required)

⸺

### Notes (Required)

bow and other items that are used with right click wont work if looking down, because of the mod trying to place blocks.

### latest.log (Required)

https://gist.github.com/lalelilolu2/7142bce152b7a8904294b36acfb6c8a6

**Comment by Fuzss** [comment]
Thanks, fixed.
